from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status

from app.core.security import current_user, require_roles
from app.schemas.api import (
    AuditResultResponse,
    AuditorDecision,
    AuditorDecisionResponse,
    SubmitClaimResponse,
    documented_errors,
)
from app.services.api_store import audits, audit_numbers, claims, identifier, now

router = APIRouter(tags=["Audits"])


def complete_audit(audit_id: str) -> None:
    audit = audits[audit_id]
    claim = claims[audit["claim_id"]]
    # Agent integration point: replace this deterministic development result with graph.invoke().
    audit.update({"audit_status": "COMPLETED", "risk_score": 0, "summary": "No findings were generated by the development audit workflow.", "findings": []})
    claim["status"] = "AUDITED"


@router.post(
    "/claims/{claim_id}/submit",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=SubmitClaimResponse,
    responses=documented_errors(401, 403, 404, 409, 422),
)
def submit_claim(
    claim_id: str,
    tasks: BackgroundTasks,
    user: dict = Depends(current_user),
):
    claim = claims.get(claim_id)
    if not claim:
        raise HTTPException(status_code=404, detail="Claim not found")
    if user["role"] == "EMPLOYEE" and claim["owner_id"] != user["sub"]:
        raise HTTPException(status_code=403, detail="Claim belongs to another employee")
    if claim["status"] != "DRAFT":
        raise HTTPException(status_code=409, detail="Only draft claims can be submitted")
    if not claim["expense_lines"]:
        raise HTTPException(status_code=422, detail="Claim requires at least one expense line")
    audit_id = identifier("AUD", audit_numbers)
    claim["status"] = "PROCESSING"
    audits[audit_id] = {"audit_id": audit_id, "claim_id": claim_id, "audit_status": "PROCESSING", "started_at": now(), "findings": []}
    tasks.add_task(complete_audit, audit_id)
    return {"claim_id": claim_id, "audit_id": audit_id, "claim_status": "PROCESSING", "message": "Claim submitted successfully. Audit is running."}


@router.get(
    "/claims/{claim_id}/audit",
    response_model=AuditResultResponse,
    responses=documented_errors(401, 403, 404),
)
def get_audit(claim_id: str, user: dict = Depends(current_user)):
    claim = claims.get(claim_id)
    if not claim:
        raise HTTPException(status_code=404, detail="Claim not found")
    if user["role"] == "EMPLOYEE" and claim["owner_id"] != user["sub"]:
        raise HTTPException(status_code=403, detail="Claim belongs to another employee")
    audit = next((item for item in audits.values() if item["claim_id"] == claim_id), None)
    if not audit:
        raise HTTPException(status_code=404, detail="No audit has been started for this claim")
    result = {key: audit[key] for key in ("audit_id", "audit_status")}
    result.update({"claim_id": claim_id, "claim_status": claim["status"]})
    if audit["audit_status"] == "PROCESSING":
        result["message"] = "Audit workflow is still running."
    else:
        result.update({key: audit[key] for key in ("risk_score", "summary", "findings")})
    return result


@router.post(
    "/audits/{audit_id}/decision",
    response_model=AuditorDecisionResponse,
    responses=documented_errors(401, 403, 404, 409, 422),
)
def make_decision(audit_id: str, payload: AuditorDecision, user: dict = Depends(require_roles("AUDITOR", "ADMIN"))):
    audit = audits.get(audit_id)
    if not audit:
        raise HTTPException(status_code=404, detail="Audit not found")
    if audit["audit_status"] != "COMPLETED":
        raise HTTPException(status_code=409, detail="Audit must complete before a decision")
    claim = claims[audit["claim_id"]]
    if claim["status"] not in {"AUDITED", "NEEDS_CLARIFICATION"}:
        raise HTTPException(status_code=409, detail="Claim is not ready for a decision")
    claim["status"] = payload.decision.value
    audit["decision"] = {"decision": payload.decision.value, "comment": payload.comment, "resolved_finding_ids": payload.resolved_finding_ids, "decision_by": user["sub"], "decision_at": now()}
    return {"audit_id": audit_id, "claim_id": claim["claim_id"], "final_status": claim["status"], "decision_by": {"user_id": user["sub"], "name": "Finance Auditor" if user["role"] == "AUDITOR" else "System Admin"}, "decision_at": audit["decision"]["decision_at"], "message": "Audit decision saved successfully."}
