"""add tax_amount to claims

Revision ID: 10c4aa1d273e
Revises: 26228978c7ca
Create Date: 2026-09-16 17:38:14.399301+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c4aa1d273e'
down_revision: Union[str, None] = '26228978c7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.execute("UPDATE claims SET tax_amount = 0 WHERE tax_amount IS NULL")
    op.alter_column('claims', 'tax_amount', existing_type=sa.Numeric(precision=14, scale=2), nullable=False, server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'tax_amount', existing_type=sa.Numeric(precision=14, scale=2), nullable=True, server_default=None)
    op.drop_column('claims', 'tax_amount')
    # ### end Alembic commands ###