"""add policy_documents table

Revision ID: 26228978c7ca
Revises: 4d301d1a6f5a
Create Date: 2026-09-16 04:26:12.599604+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26228978c7ca'
down_revision: Union[str, None] = '4d301d1a6f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_documents',
    sa.Column('policy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id', name=op.f('pk_policy_documents'))
    )
    op.create_index(op.f('ix_policy_documents_doc_hash'), 'policy_documents', ['doc_hash'], unique=True)
    op.create_foreign_key(op.f('fk_policy_chunking_policy_id_policy_documents'), 'policy_chunking', 'policy_documents', ['policy_id'], ['policy_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_policy_chunking_policy_id_policy_documents'), 'policy_chunking', type_='foreignkey')
    op.drop_index(op.f('ix_policy_documents_doc_hash'), table_name='policy_documents')
    op.drop_table('policy_documents')
    # ### end Alembic commands ###