"""add ai run status and ai decision to claims

Revision ID: eb26ffaee5ae
Revises: 10c4aa1d273e
Create Date: 2026-09-16 17:45:42.801302+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'eb26ffaee5ae'
down_revision: Union[str, None] = '10c4aa1d273e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ai_run_status').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('APPROVE', 'REJECT', 'REVIEW', name='ai_decision').create(op.get_bind(), checkfirst=True)
    op.add_column('claims', sa.Column('ai_run_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ai_run_status', create_type=False), nullable=True))
    op.add_column('claims', sa.Column('ai_decision', sa.Enum('APPROVE', 'REJECT', 'REVIEW', name='ai_decision', create_type=False), nullable=True))
    op.execute("UPDATE claims SET ai_run_status = 'PENDING' WHERE ai_run_status IS NULL")
    op.alter_column('claims', 'ai_run_status', existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ai_run_status', create_type=False), nullable=False, server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'ai_run_status', existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ai_run_status', create_type=False), nullable=True, server_default=None)
    op.drop_column('claims', 'ai_decision')
    op.drop_column('claims', 'ai_run_status')
    postgresql.ENUM('APPROVE', 'REJECT', 'REVIEW', name='ai_decision').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ai_run_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###